# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e5bbc1a5546b86d2f30b91c729ea511b79fc8103deb2822305cf8bfa291e2f546c2ac3da88aa29ef09ce8b6d556cd50fd34fda7c86b722525b9ddb00d1f19d8a

test:
  secret_key_base: b6150c6492d05a16d113af76685c1d94eb751badf22c42bab236e3304a15c1e2b34fd04dec33dc9e4aa02485a67c3a5a28ffb6ba2ca87a130ca2c648caee0e02

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
